kind: ConfigMap
apiVersion: v1
metadata:
  name: zen-alert-cp4d-watsonstudio-job-info-monitor-extension
  labels:
    app: zen-adv
    icpdata_addon: 'true'
    icpdata_addon_version: 4.3.0
    release: zen-adv
data:
  extensions: |
    [
      {
        "extension_point_id": "zen_alert_monitor",
        "extension_name": "zen_alert_cp4d_watsonstudio_job_info",
        "display_name": "Watson Stuido Job Info",
        "details": {
          "name": "cp4d-watsonstudio-job-info",
          "image": "${OPENSHIFT_IMAGE_REGISTRY}/cp4d-watsonstudio-job-info:latest",
          "schedule": "*/4 * * * *",
          "event_types": [
            {
              "name": "cp4d_watsonstudio_jobs_overall_count",
              "simple_name": "Watson Stuido Jobs Overall Count",
              "alert_type": "platform",
              "short_description": "CP4D Watson Stuido Jobs Overall Count",
              "long_description": "CP4D Watson Stuido Jobs Overall Count: <cp4d_watsonstudio_jobs_overall_count>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },              
            {
              "name": "cp4d_watsonstudio_active_jobs_overall_count",
              "simple_name": "Watson Studio Runtime Active Jobs Overall Count",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Runtime Active Jobs Overall Count",
              "long_description": "CP4D Watson Studio Runtime Active Jobs Overall Count: <cp4d_watsonstudio_active_jobs_overall_count>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },
            {
              "name": "cp4d_watsonstudio_jobs_project_count",
              "simple_name": "Watson Studio Jobs Project Count",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio c",
              "long_description": "CP4D Watson Studio Jobs Project Count: <cp4d_watsonstudio_jobs_project_count>",
              "resolution": "none",
              "reason_code_prefix": "80"
            },
            {
              "name": "cp4d_watsonstudio_active_jobs_project_count",
              "simple_name": "Watson Studio Runtime Active Jobs Project Count",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Runtime Active Jobs Project Count",
              "long_description": "CP4D Watson Studio Runtime Active Jobs Project Count: <cp4d_watsonstudio_active_jobs_project_count>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },
            {
              "name": "cp4d_watsonstudio_job_last_status",
              "simple_name": "Watson Studio Job Last Status",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Job Last Status",
              "long_description": "CP4D Watson Studio Job Last Status: <cp4d_watsonstudio_job_last_status_success>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            }
          ]
        }
      }
    ]