kind: ConfigMap
apiVersion: v1
metadata:
  name: zen-alert-cp4d-watsonstudio-runtime-usage-monitor-extension
  labels:
    app: zen-adv
    icpdata_addon: 'true'
    icpdata_addon_version: 4.3.0
    release: zen-adv
data:
  extensions: |
    [
      {
        "extension_point_id": "zen_alert_monitor",
        "extension_name": "zen_alert_monitor_cp4d_watsonstudio_runtime_usage",
        "display_name": "Watson Stuido Runtime Usage",
        "details": {
          "name": "cp4d-watsonstudio-runtime-usage",
          "image": "${OPENSHIFT_IMAGE_REGISTRY}/cp4d-watsonstudio-runtime-usage:latest",
          "schedule": "*/3 * * * *",
          "event_types": [
            {
              "name": "cp4d_watsonstudio_runtime_usage_total_count",
              "simple_name": "Watson Stuido Runtime Usage Total Count",
              "alert_type": "platform",
              "short_description": "CP4D Watson Stuido Runtime Usage Total Count",
              "long_description": "CP4D Watson Stuido Runtime Usage Total Count: <cp4d_watsonstudio_runtime_usage_total_count>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },              
            {
              "name": "cp4d_watsonstudio_runtime_usage_project_count",
              "simple_name": "Watson Studio Runtime Usage Project Count",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Runtime Usage Project Count",
              "long_description": "CP4D Watson Studio Runtime Usage Project Count: <cp4d_watsonstudio_runtime_usage_project_count>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },
            {
              "name": "cp4d_watsonstudio_runtime_usage_project_cpu_limit",
              "simple_name": "Watson Studio Runtime Usage Project CPU Limit",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Runtime Usage Project CPU Limit",
              "long_description": "CP4D Watson Studio Runtime Usage Project CPU Limit: <cp4d_watsonstudio_runtime_usage_project_cpu_limit>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },
            {
              "name": "cp4d_watsonstudio_runtime_usage_project_memory",
              "simple_name": "Watson Studio Runtime Usage Project Memory",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Runtime Usage Project Memory",
              "long_description": "CP4D Watson Studio Runtime Usage Project Memory: <cp4d_watsonstudio_runtime_usage_project_memory_limit>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },
            {
              "name": "cp4d_watsonstudio_runtime_usage_cpu",
              "simple_name": "Watson Studio Runtime Usage CPU",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Runtime Usage CPU",
              "long_description": "CP4D Watson Studio Runtime Usage CPU: <cp4d_watsonstudio_runtime_usage_cpu_limit>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            },
            {
              "name": "cp4d_watsonstudio_runtime_usage_memory",
              "simple_name": "Watson Studio Runtime Usage Memory",
              "alert_type": "platform",
              "short_description": "CP4D Watson Studio Runtime Usage Memory",
              "long_description": "CP4D Watson Studio Runtime Usage Memory Limit=<cp4d_watsonstudio_runtime_usage_memory_limit>",                
              "resolution": "none",
              "reason_code_prefix": "80"
            }
          ]
        }
      }
    ]